version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: lewis-loyalty-mongodb
    restart: unless-stopped
    ports:
      - "27020:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: lewis-loyalty
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    networks:
      - lewis-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/lewis-loyalty --quiet
      interval: 10s
      timeout: 5s
      retries: 5

  # MongoDB Express - Web UI for MongoDB (optional)
  mongo-express:
    image: mongo-express:latest
    container_name: lewis-loyalty-mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password123
      ME_CONFIG_MONGODB_URL: mongodb://admin:password123@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    depends_on:
      - mongodb
    networks:
      - lewis-network

volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local

networks:
  lewis-network:
    driver: bridge
